// Menu items data for drinks and foods
export const store = [
  {
    id: 1,
    uri: require('../assets/images/drinks/orange-juice.png'),
    name: 'Zobo',
    price: 500,
    category: 'Traditional',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 2,
    uri: require('../assets/images/drinks/fruit-juice.png'),
    name: 'Kunu',
    price: 400,
    category: 'Traditional',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 3,
    uri: require('../assets/images/drinks/orange-juice.png'),
    name: 'Palm Wine',
    price: 300,
    category: 'Traditional',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 4,
    uri: require('../assets/images/drinks/fruit-juice.png'),
    name: 'Fayrouz',
    price: 250,
    category: 'Soft Drink',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 5,
    uri: require('../assets/images/drinks/orange-juice.png'),
    name: 'Maltina',
    price: 200,
    category: 'Soft Drink',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 6,
    uri: require('../assets/images/drinks/orange-juice.png'),
    name: 'Chapman',
    price: 600,
    category: 'Cocktail',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 7,
    uri: require('../assets/images/drinks/fruit-juice.png'),
    name: 'Orange Juice',
    price: 350,
    category: 'Juice',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 8,
    uri: require('../assets/images/drinks/orange-juice.png'),
    name: 'Ginger Beer',
    price: 450,
    category: 'Traditional',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 9,
    uri: require('../assets/images/drinks/fruit-juice.png'),
    name: 'Pepsi',
    price: 150,
    category: 'Soft Drink',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 10,
    uri: require('../assets/images/drinks/orange-juice.png'),
    name: 'Coca-Cola',
    price: 150,
    category: 'Soft Drink',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 11,
    uri: require('../assets/images/drinks/fruit-juice.png'),
    name: 'Espresso',
    price: 300,
    category: 'Coffee',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 12,
    uri: require('../assets/images/drinks/orange-juice.png'),
    name: 'Latte',
    price: 350,
    category: 'Coffee',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 13,
    uri: require('../assets/images/drinks/fruit-juice.png'),
    name: 'Green Tea',
    price: 250,
    category: 'Tea',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 14,
    uri: require('../assets/images/drinks/orange-juice.png'),
    name: 'Black Tea',
    price: 200,
    category: 'Tea',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 15,
    uri: require('../assets/images/drinks/fruit-juice.png'),
    name: 'Smoothie',
    price: 500,
    category: 'Smoothie',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 16,
    uri: require('../assets/images/drinks/orange-juice.png'),
    name: 'Milkshake',
    price: 450,
    category: 'Milkshake',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 17,
    uri: require('../assets/images/drinks/fruit-juice.png'),
    name: 'Energy Drink',
    price: 400,
    category: 'Energy Drink',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 18,
    uri: require('../assets/images/drinks/orange-juice.png'),
    name: 'Sparkling Water',
    price: 300,
    category: 'Water',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 19,
    uri: require('../assets/images/drinks/fruit-juice.png'),
    name: 'Still Water',
    price: 200,
    category: 'Water',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 20,
    uri: require('../assets/images/drinks/orange-juice.png'),
    name: 'Matcha Latte',
    price: 400,
    category: 'Tea',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 21,
    uri: require('../assets/images/drinks/fruit-juice.png'),
    name: 'Cappuccino',
    price: 350,
    category: 'Coffee',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 22,
    uri: require('../assets/images/drinks/orange-juice.png'),
    name: 'Iced Tea',
    price: 300,
    category: 'Tea',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 23,
    uri: require('../assets/images/drinks/fruit-juice.png'),
    name: 'Mango Juice',
    price: 350,
    category: 'Juice',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 24,
    uri: require('../assets/images/drinks/orange-juice.png'),
    name: 'Pineapple Juice',
    price: 350,
    category: 'Juice',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 25,
    uri: require('../assets/images/drinks/fruit-juice.png'),
    name: 'Americano',
    price: 300,
    category: 'Coffee',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 26,
    uri: require('../assets/images/drinks/orange-juice.png'),
    name: 'Banana Smoothie',
    price: 600,
    category: 'Smoothie',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 27,
    uri: require('../assets/images/drinks/fruit-juice.png'),
    name: 'Orijin',
    price: 500,
    category: 'Traditional',
    department: 'drink',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 1,
    uri: require('../assets/images/foods/rice.png'),
    name: 'Jollof Rice',
    price: 1000,
    category: 'Main Course',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 2,
    uri: require('../assets/images/foods/spaghetti.png'),
    name: 'Fried Rice',
    price: 1200,
    category: 'Main Course',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 3,
    uri: require('../assets/images/foods/rice.png'),
    name: 'Egusi Soup',
    price: 1500,
    category: 'Soup',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 4,
    uri: require('../assets/images/foods/spaghetti.png'),
    name: 'Vegetable Soup',
    price: 1400,
    category: 'Soup',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 5,
    uri: require('../assets/images/foods/rice.png'),
    name: 'Pepper Soup',
    price: 800,
    category: 'Appetizer',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 6,
    uri: require('../assets/images/foods/spaghetti.png'),
    name: 'Suya',
    price: 500,
    category: 'Snack',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 7,
    uri: require('../assets/images/foods/rice.png'),
    name: 'Moi Moi',
    price: 300,
    category: 'Side Dish',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 8,
    uri: require('../assets/images/foods/spaghetti.png'),
    name: 'Akara',
    price: 200,
    category: 'Snack',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 9,
    uri: require('../assets/images/foods/rice.png'),
    name: 'Pounded Yam',
    price: 500,
    category: 'Side Dish',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 10,
    uri: require('../assets/images/foods/spaghetti.png'),
    name: 'Eba',
    price: 400,
    category: 'Side Dish',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 11,
    uri: require('../assets/images/foods/rice.png'),
    name: 'Amala',
    price: 450,
    category: 'Side Dish',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 12,
    uri: require('../assets/images/foods/spaghetti.png'),
    name: 'Fried Plantain',
    price: 300,
    category: 'Side Dish',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 13,
    uri: require('../assets/images/foods/rice.png'),
    name: 'Grilled Chicken',
    price: 1000,
    category: 'Protein',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 14,
    uri: require('../assets/images/foods/spaghetti.png'),
    name: 'Beef',
    price: 800,
    category: 'Protein',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 15,
    uri: require('../assets/images/foods/rice.png'),
    name: 'Grilled Fish',
    price: 1200,
    category: 'Protein',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 16,
    uri: require('../assets/images/foods/spaghetti.png'),
    name: 'Salad',
    price: 600,
    category: 'Side Dish',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 17,
    uri: require('../assets/images/foods/rice.png'),
    name: 'Bread',
    price: 200,
    category: 'Snack',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 18,
    uri: require('../assets/images/foods/spaghetti.png'),
    name: 'Boiled Yam',
    price: 400,
    category: 'Side Dish',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 19,
    uri: require('../assets/images/foods/rice.png'),
    name: 'Yam Porridge',
    price: 700,
    category: 'Main Course',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 20,
    uri: require('../assets/images/foods/spaghetti.png'),
    name: 'Spaghetti',
    price: 900,
    category: 'Main Course',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 21,
    uri: require('../assets/images/foods/rice.png'),
    name: 'Beans',
    price: 500,
    category: 'Main Course',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 22,
    uri: require('../assets/images/foods/spaghetti.png'),
    name: 'Okra Soup',
    price: 1300,
    category: 'Soup',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 23,
    uri: require('../assets/images/foods/rice.png'),
    name: 'Peppered Snail',
    price: 2000,
    category: 'Appetizer',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 24,
    uri: require('../assets/images/foods/spaghetti.png'),
    name: 'Peppered Chicken',
    price: 1500,
    category: 'Protein',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 25,
    uri: require('../assets/images/foods/rice.png'),
    name: 'Peppered Fish',
    price: 1800,
    category: 'Protein',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 26,
    uri: require('../assets/images/foods/spaghetti.png'),
    name: 'Amala with Ewedu and Gbegiri',
    price: 1200,
    category: 'Main Course',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 27,
    uri: require('../assets/images/foods/rice.png'),
    name: 'Pounded Yam and Egusi Soup',
    price: 1500,
    category: 'Main Course',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 28,
    uri: require('../assets/images/foods/spaghetti.png'),
    name: 'Catfish Pepper Soup',
    price: 1800,
    category: 'Soup',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 29,
    uri: require('../assets/images/foods/rice.png'),
    name: 'Gizdodo',
    price: 1000,
    category: 'Side Dish',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 30,
    uri: require('../assets/images/foods/spaghetti.png'),
    name: 'Jollof Rice with Chicken',
    price: 1500,
    category: 'Main Course',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 31,
    uri: require('../assets/images/foods/rice.png'),
    name: 'Okro Soup with Semo',
    price: 1300,
    category: 'Soup',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 32,
    uri: require('../assets/images/foods/spaghetti.png'),
    name: 'Beef Burger',
    price: 1600,
    category: 'Snack',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
  {
    id: 33,
    uri: require('../assets/images/foods/rice.png'),
    name: 'Egg Roll',
    price: 400,
    category: 'Snack',
    department: 'food',
    quantity: 1,
    reviewers: [
      {
        id: 1,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 2,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 3,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
      {
        id: 4,
        uri: require('../assets/images/reviewers/review-1.png'),
        name: 'Femi Mayowa',
        rating: '4.5',
      },
    ],
  },
];

export const users = [
  {
    id: 1,
    name: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    phone: '+1234567890',
    address: '123 Maple St, Springfield, IL',
    orderHistory: [
      {
        orderId: 101,
        items: [
          { name: 'Cheeseburger', quantity: 2, price: 5.99 },
          { name: 'Fries', quantity: 1, price: 2.49 },
          { name: 'Coca-Cola', quantity: 2, price: 1.01 },
        ],
        totalPrice: 9.49,
        date: '2025-05-01',
        status: 'Delivered',
      },
      {
        orderId: 102,
        items: [
          { name: 'Margherita Pizza', quantity: 1, price: 8.99 },
          { name: 'Lemonade', quantity: 1, price: 2.49 },
        ],
        totalPrice: 11.48,
        date: '2025-05-04',
        status: 'Pending',
      },
    ],
  },
  {
    id: 2,
    name: 'Bob Smith',
    email: 'bob.smith@example.com',
    phone: '+1987654321',
    address: '456 Oak Rd, Lincoln, NE',
    orderHistory: [
      {
        orderId: 103,
        items: [
          { name: 'Chicken Sandwich', quantity: 1, price: 6.99 },
          { name: 'French Fries', quantity: 1, price: 2.49 },
          { name: 'Pepsi', quantity: 1, price: 1.89 },
        ],
        totalPrice: 11.37,
        date: '2025-05-02',
        status: 'Delivered',
      },
      {
        orderId: 104,
        items: [
          { name: 'Spaghetti Bolognese', quantity: 1, price: 9.49 },
          { name: 'Iced Tea', quantity: 1, price: 2.19 },
        ],
        totalPrice: 11.68,
        date: '2025-05-06',
        status: 'Cancelled',
      },
    ],
  },
  {
    id: 3,
    name: 'Carla Rivera',
    email: 'carla.rivera@example.com',
    phone: '+1098765432',
    address: '789 Pine Ln, Denver, CO',
    orderHistory: [
      {
        orderId: 105,
        items: [
          { name: 'Veggie Burger', quantity: 1, price: 7.99 },
          { name: 'Sweet Potato Fries', quantity: 1, price: 3.49 },
          { name: 'Apple Juice', quantity: 1, price: 2.29 },
        ],
        totalPrice: 13.77,
        date: '2025-05-03',
        status: 'Delivered',
      },
    ],
  },
];
